image: conda/miniconda3

stages:
  - lint
  - test
  - build
  - deploy

lint:
  stage: lint
  script:
    - apt update && apt install -y gcc
    - conda install python=3.6 psutil numpy cython
    - pip install -e .
    - pip install "pydocstyle<4" flake8 pep8-naming flake8-docstrings
    - flake8 --config=.flake8 scared tests setup.py

test:
  stage: test
  script:
    - apt update && apt install -y gcc
    - conda install python=3.6 psutil pycrypto numpy cython
    - python setup.py test -v


build:pypi:
  stage: build
  script:
    - apt update && apt install -y gcc
    - conda install python=3.6 numpy cython numba
    - pip install -U pip setuptools
    - python setup.py build_ext --inplace
    - python setup.py sdist
  only:
    - tags
  artifacts:
    paths:
      - "dist/*"

deploy:pypi:
  stage: deploy
  only:
    - tags
  when: manual
  script:
    - conda install python=3.6 psutil cython numpy numba
    - pip install -U pip setuptools twine
    - twine upload --repository-url $PYPI_REPOSITORY dist/*  -u $PYPI_USERNAME -p $PYPI_PWD

build:conda:
  stage: build
  script:
    - apt update && apt install -y gcc
    - conda install python=3.6 conda-build conda-verify
    - conda config --add channels $ANACONDA_CHANNEL
    - conda build --output-folder out .recipe
  only:
    - tags
  artifacts:
    paths:
      - "out/*/*.tar.bz2"

deploy:conda:
  stage: deploy
  script:
    - conda config --add channels $ANACONDA_CHANNEL
    - conda install anaconda-client
    - anaconda login --username $ANACONDA_USERNAME --password $ANACONDA_PWD
    - anaconda upload out/noarch/scared*.tar.bz2
    - anaconda logout
  only:
    - tags
  when: manual
  artifacts:
    paths:
      - "out/*/*.tar.bz2"

pages:
  stage: build
  script:
    - apt update && apt install -y gcc
    - conda install python=3.6 psutil numpy cython
    - pip install -e .
    - cd docs
    - ./build_doc.sh
  artifacts:
    paths:
    - public
  only:
    - tags
