{% set version = "0.8.0" %}

package:
  name: scared
  version: {{ version }}

source:
  path: ../

build:
  number: 0
  noarch: python

requirements:
  build:
    - wheel
    - pip
    - setuptools
    - {{ compiler('c') }}
  host:
    - python {{ python }}
    - cython
    - estraces
    - numpy
  run:
    - python
    - cython
    - numpy
    - estraces
    - psutil
    - numba
    - scipy
about:
  home: https://gitlab.com/eshard/scared
  license: GNU LGPL V3
  license_file: LICENSE
  summary: scared is a side-channel analysis framework.
